### PR TITLE
Create store

### LINKED ISSUE #27: Create a store page
follow: https://github.com/Abbe-and-Gabbe/jkpgCity/blob/main/JKPGCITY.pdf

### PR DESCRIPTION
**Pull request by albin02forsberg**

### CODE REVIEW

**Review by GabrielAdward — COMMENTED** [review]
Looks good, currently when creating a new store it creates two of the same.

**Comment by albin02forsberg** [comment]
@GabrielAdward How do you replicate it? It only creates one on my machine...?

**Comment by GabrielAdward** [comment]
> @GabrielAdward How do you replicate it? It only creates one on my machine...?

1. Click on create a new store 
2. fill in the fields then click on create store 
3. click on ok at the pop up and the you will be redirected to store page
4. navigate to the last page and there will be two of the same store that you created

**Comment by albin02forsberg** [comment]
> > @GabrielAdward How do you replicate it? It only creates one on my machine...?
> 
> 1. Click on create a new store
> 2. fill in the fields then click on create store
> 3. click on ok at the pop up and the you will be redirected to store page
> 4. navigate to the last page and there will be two of the same store that you created

Fixed, was a doublicate line in the `storesModel`...

**Review by GabrielAdward — APPROVED** [review]
LGTM!

**Pull request merged**
